server:
    port: 8080
    shutdown: graceful

spring:
    main:
        banner-mode: 'off'
    profiles:
        active: default
    flyway:
        enabled: true
        baseline-on-migrate: true
    datasource:
        url: "jdbc:postgresql://db:5432/postgres"
        username: "postgres"
        password: "postgres"